### PR TITLE
Travis and Mono

### PR DESCRIPTION
**Pull request by rykerwilliams**
Remove incompatible SL5 project. 

```
 Update to build on Travis. 
```

### CODE REVIEW

**Comment by rykerwilliams** [comment]
Are we going to continue to support SL5? 

From my commit: The goal of targeting SL5 is counter to the goal of targeting Mono, as SL5 is not supported by Moonlight (www.mono-project.com/docs/web/moonlight/) and ML in general is no longer supported.

**Comment by vdaron** [comment]
@mirthy What are tour thoughts about SL5 ? It doesn't seems to be a prior target to me. 
Continuous automation seems to be already configured with wercker any advantage to use travis ? (I'm really not an expert of CI :-))

**Comment by rykerwilliams** [comment]
Ok so the CI is wercker? I saw the .travis.yml files and thought the CI was
Travis. The .io page uses badges currently from Travis (for mono) and
Appveyor (windows).

Is there a wercker.yml I am missing? I was unfamiliar with Travis and
Wercker until a week ago, so I don't express a preference either way. I was
more interested in getting them up to date and building, whatever the
CI, with the end goal to update the build badges for new visitors. Site
looks stale right now imo.

**Comment by rykerwilliams** [comment]
I opened an issue on the main project to discuss the CI portion of this pull request: https://github.com/NServiceKit/NServiceKit/issues/33

I don't think it makes sense to discuss that more here.

Perhaps we can agree to remove the project from the solution, as is done in the pull request? I'm not actually removing any code files. If so, I'll create a new pull request with just those changes and close this one.

**Comment by rykerwilliams** [comment]
Closing this pull request in favor of a more succinct branch which discrete commits for each improvement.

**Pull request closed without merging**
